Function to implement Alexandre-Theophile Vandermonde

In [5]:
import numpy as np
x=np.array([1,2,3,5])
N=4
result=np.vander(x,N)

print(result)

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
